### ISSUE TITLE
发现bug-关于BothView和Tabbar的

### ISSUE THREAD

**Issue by ADE150** [XiLaiTL/typora-theme-bothview-tabbar#1]
### 问题1：标题高度过高时，会缺少两个标题
BothView中，如果标题个数超过盒子高度，盒子底部会缺少显示两个标题。
#### 解决方法：在Bothview.css中添加以下代码可解决
```CSS
#outline-content {
    margin-top: -54px;
    padding-top: 20px;
    padding-bottom: 20px;
}
```

### 问题2：tabbar空白，无法显示
下载tabbar后，使用并重启，页面标签部分一片空白。原因未知。
求助解决方法！情况如下（源文件未改动）
![image](https://user-images.githubusercontent.com/84427028/170882695-1789f57a-521f-447e-8cb9-56da65f6bcd8.png)

如果能够解决，请联系2970131569@qq.com，我很喜欢你的Typora样式！

**Comment by XiLaiTL** [comment]
Would you mind providing the screenshot of the first bug?
第一个问题有截图可以看一下吗？

When you toggle sidebar using the TabBar theme, **you need to click "Files" and switch to files list firstly**
第二个问题，你需要首先打开侧边栏-文件一次。当切换为大纲或者文件树状图的时候，这个标签栏还继续保持在上方。

Thanks!

**Comment by ADE150** [comment]
## 关于问题1
> About the first bug

详细描述：大纲所需高度大于侧边栏1个高度的时候，就会缺少两个底部标题，如下图，末尾本应有两个名为“Test Title 07”和“Test Title 08”的标题，但在右边大纲未显示（滚动条表示大纲已经到底了）：

![image](https://user-images.githubusercontent.com/84427028/171027020-ab5012f3-9235-4a8b-a70f-d8928bfcbb33.png)

另外，左边侧边栏切换至大纲视图并没有此问题：

![image](https://user-images.githubusercontent.com/84427028/171027145-21077058-fe24-4d61-aaa2-bc888672f3d2.png)

## 关于问题2
> About the second bug

在我发消息之前，我已经对它进行了各种尝试，包括但不限于“来回切换‘侧边栏-文件’和‘侧边栏-大纲’”，重启，最小化，查看源码尝试找出错误。遗憾的是，标签视图仍然是一个空白方块，而我却找不到任何问题。如下：

- 文件视图：

![image](https://user-images.githubusercontent.com/84427028/171027736-138ede91-27e3-4921-ad05-ddea644d1154.png)

- 大纲视图：

![image](https://user-images.githubusercontent.com/84427028/171027750-f9c2d7ac-99bd-41dc-88cd-2f75699632ed.png)

如果大家没有此问题产生，我想可能是Typora版本的问题，或者是电脑不适配某些东西，但是目前暂时想不到。

> 补充：
> 
> 我的Typora版本号是1.2.4（2022年3月），Windows 10 家庭版 联想Y7000p。我对电脑和网页前端的经验不多，希望能帮到您。
> 
> 还有希望您不要介意我仅用中文回复（英语不好，见谅）。

**Comment by ADE150** [comment]
刚看到邮件，第二个问题解决了

**Comment by ADE150** [comment]
第一个问题的产生原因可能是因为 `#outline-content` 的 div 在 `.sidebar-content` 下，而 `.sidebar-content` 为了给“文件”和“大纲”标签栏留位置，所以设了 `margin` 或者其他，把大纲的文字部分“挤下去”了，导致最后两个标题无法在右侧大纲显示。

![image](https://user-images.githubusercontent.com/84427028/171071018-cae7ec02-ffff-444b-8c83-d70b3ff35459.png)

我的做法是去除 `margin`，于是我在 `bothview.css` 下添加以下代码：
```CSS
#outline-content {
    margin-top: -54px;
    padding-top: 54px;
    padding-bottom: 20px;
}
```

我的能力有限，目前没想到更好方法，这个方法已经能解决我的问题了。

**Comment by XiLaiTL** [comment]
实在是感谢！
我发现应该是position出问题了。原来的top是0，因为position不是fixed，所以高度顺延下来，内容没有缺少。
移动到右边只有由于position是fixed，父亲高度是54px，所以内容顺延下了54px，就刚好少了54px。
可以测试一下添加top: 0px; 刚刚好可以看到所有标题。

解决方案可以是你的方式
也可以如下操作：在.pin-outline .active-tab-files #outline-content下
方案二：padding-bottom: 84px; /* 54+footbar 30*/
方案三：height: 87%
