### ISSUE TITLE
文件栏总有空白

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [XiLaiTL/typora-theme-bothview-tabbar#4]
使用 `both-view` 的情况下，左侧文件管理器总是有空白，必须向右边滚动才能让文件视图处于正常的位置：

<img width="232" alt="image" src="https://user-images.githubusercontent.com/22313057/230598221-6930d362-733c-4062-b60b-e0ecef514f45.png">

有没有什么办法能让其左侧对齐，就像Typora默认那样？

<img width="231" alt="image" src="https://user-images.githubusercontent.com/22313057/230598277-b1fae5ff-ab8b-4cf7-a845-80dd4cc74fc0.png">

MBP14 M1Pro Venture 13.3 最新的Typora

**Comment by XiLaiTL** [comment]
#2

**Comment by Lawrence-of-AnKing** [comment]
> #2

大佬，看看啥原因，能不能解决一下，解决了这就完美了。

这主题关掉，关联 [#2](https://github.com/XiLaiTL/typora-theme-bothview-tabbar/issues/2)
