### ISSUE TITLE
引入bothview.css 左侧文件树无法拉伸宽度

### ISSUE THREAD

**Issue by carve-myself** [XiLaiTL/typora-theme-bothview-tabbar#6]
引入bothview.css 左侧文件树无法拉伸宽度

**Comment by XiLaiTL** [comment]
可以的，我设计的是，左侧和右侧同时拉伸，bothview拉伸的位置是：

> When using BothView theme, you can modify the sidebar size by dragging the resizer bar at the bottom between the footer and the sidebar, but when using TabBar theme, you need to find the resizer bar at the top.

在脚栏和侧边栏之间有一个浅浅的位置，你用鼠标移动上去
