### ISSUE TITLE
大纲放到右侧之后，上面这块空白处，请问怎么样可以添加和左侧一样的  大纲  字样？

### ISSUE THREAD

**Issue by magiceses** [XiLaiTL/typora-theme-bothview-tabbar#7]
<img width="520" alt="image" src="https://github.com/XiLaiTL/typora-theme-bothview-tabbar/assets/50326171/eb2a0995-2182-44c2-8918-86ac3c928dc5">
大纲放到右侧之后，上面这块空白处，请问怎么样可以添加和左侧一样的  大纲  字样？不然一片空白看着怪怪的

**Comment by XiLaiTL** [comment]
本来是打算把查找弄到那边过去的，然后现在有点懒惰，要不你试一下？把查找弄过去好像也不错的样子

**Comment by magiceses** [comment]
不太会前端，简单调了下，往上挪了挪，多谢
